### ISSUE TITLE
Dear Mr Strommer

### ISSUE THREAD

**Issue by SpodoY** [mstrommer/ALDA_Exercise4v12022#1]
![6j54mf](https://user-images.githubusercontent.com/72346498/172912533-9a080ac7-feb9-4674-94b0-f3d3a9b57ce4.jpg)
![among-us-twerk](https://user-images.githubusercontent.com/72346498/172912877-59545be4-8472-467c-b9fa-d9dac71b7b7d.gif)

**Comment by waldifubu** [comment]
??? What's the issue?

**Comment by SpodoY** [comment]
Thanks
